### ISSUE TITLE
Version 3.x Tracking

### ISSUE THREAD

**Issue by drasticactions** [drasticactions/FishyFlip#97]
2024/11/22 Update:

I've removed FishyFlipDX and have merged it into the main codebase. I think it's safe enough now for a wide audience. I've ported the existing test suite over and they all pass, but there are tons of new endpoints (Ex. Ozone) that I have not tried before, and I'm not sure how much people actively care about it.

I am also updating the documentation to reflect the new APIs. Since I still need the existing docs for the stable version, they are not live yet, but you can see the [raw markdown here](https://github.com/drasticactions/FishyFlip/tree/develop/website/docs). I've written new docs for how `Result` works, `ATObject`, and more on some basic operations for how to do things. 

There's still more to do: FFSourceGen works, but the codebase is insane and I need to clean it up. It also needs to be automated against the lexicon when it updates (right now it's whenever I run the program on my machine, against whatever one I happen to be using. I'll probably make it a submodule and bump that, but I don't want people to _need_ it so we'll see. Likewise, a full list of breaking changes would be nice. 

But the API should be stable, I don't anticipate changing it. It should be safe to upgrade and try it out. And please, if you find issues, don't hesitate to file issues or PRs to help. Thanks!

----

- [x] Generate endpoints
- [x] Generate hard casts for `union` types where required
- [ ] Generate Lexicon tests based on mocked data from atproto repo
- [x] Update existing samples and documentation
- [ ] Productize FFSourceGen as a generic lexicon maker?

(and probably more to be added as I think of it)

Hey folks!

First, thank you for checking out this library; I appreciate the feedback and the pull requests to help fill out the APIs! 

I wasn't planning on making version 3.0 so soon, but I was inspired to make some bold changes that hopefully solve many issues at once. 

[FFSourceGen](https://github.com/drasticactions/FishyFlip/tree/develop/tools/FFSourceGen) is a work-in-progress CLI application for generating C# classes out of the [atproto](https://github.com/bluesky-social/atproto) lexicon. I'm designing it to work with other lexicon implementations (Ex. WhiteWind) to make jumpstarting new bindings easier. The codebase still needs a ton of work (Like not looking like a two-day hackathon project), but it's a start.

I wanted to avoid testing these bindings against the currently shipping FishyFlip. I had made many off-the-cuff decisions when coming up with the object names and layout, and trying to map to the original structure for these bindings would be difficult, if not impossible, in the long term.

So, for testing, I created [FishyFlipDX](https://github.com/drasticactions/FishyFlip/tree/develop/src/FishyFlipDX) as the testing surface. It intends to try out these bindings in the open for feedback before being merged into FishyFlip itself. 

The general structure of the bindings is to keep the "namespaces" and "classes" of the underlying lexicon IDs in C# namespaces. For example:

https://github.com/bluesky-social/atproto/blob/main/lexicons/app/bsky/actor/profile.json

becomes

`FishyFlip.Lexicon.App.Bsky.Actor.Profile`
https://github.com/drasticactions/FishyFlip/blob/develop/src/FishyFlipDX/Lexicon/App/Bsky/Actor/Profile.g.cs

While the namespaces are a little strange for C#, they make finding objects against the lexicon easier through type-ahead. With FishyFlip, I had everything be flat as `Model,` I do not feel it works well for generated code. While a breaking change like this is enormous, it will be worth it in the long term.

I anticipate little, if any, changes when accessing the data itself. So far, I have ported `ATWebSocketProtocol` (The Firehose) and `ATJetstream`. Apart from a single change from `ATRecord` to `ATObject,` everything else is the same. I expect the same for `ATProtocol,` too, as I mostly mapped my names to the ones in the lexicon and followed their parameter structure. I'll keep everyone updated as I work through it.

I **highly encourage** those running the firehose or jetstream to try out FishyFlipDX and give feedback. If there are missing types, null values, exceptions, or other weirdness, please don't hesitate to file feedback! `FFSourceGen` is being heavily refactored as I figure out the details, so expect churn.
